#!/bin/bash

echo "================================================"
echo "   Supabase 项目重建指南"
echo "================================================"
echo ""
echo "步骤 1: 创建新的 Supabase 项目"
echo "----------------------------------------------"
echo "1. 访问: https://supabase.com"
echo "2. 注册/登录账号"
echo "3. 点击 'New Project'"
echo "4. 填写项目信息:"
echo "   - Name: app-7cdqf07mbu9t (或自定义)"
echo "   - Database Password: 设置一个强密码"
echo "   - Region: 选择 Northeast Asia (Tokyo) 或最近的区域"
echo "5. 等待项目创建完成 (约2-3分钟)"
echo ""
echo "步骤 2: 获取项目配置"
echo "----------------------------------------------"
echo "1. 进入项目后，点击左侧 'Settings' -> 'API'"
echo "2. 复制以下信息:"
echo "   - Project URL (例如: https://xxx.supabase.co)"
echo "   - anon public key"
echo ""
echo "步骤 3: 更新本地配置"
echo "----------------------------------------------"
echo "1. 打开 .env 文件"
echo "2. 替换以下配置:"
echo "   TARO_APP_SUPABASE_URL=你的Project URL"
echo "   TARO_APP_SUPABASE_ANON_KEY=你的anon key"
echo "   VITE_SUPABASE_URL=你的Project URL"
echo "   VITE_SUPABASE_ANON_KEY=你的anon key"
echo ""
echo "步骤 4: 应用数据库迁移"
echo "----------------------------------------------"
echo "1. 在 Supabase 后台，点击 'SQL Editor'"
echo "2. 点击 'New query'"
echo "3. 依次执行以下migration文件 (按编号顺序):"
echo "   - supabase/migrations/00468_step1_create_new_tables.sql"
echo "   - supabase/migrations/00474_step2_final_migration.sql"
echo "   - supabase/migrations/00596_optimize_permission_tables_add_role_to_users.sql"
echo "   - supabase/migrations/00598_optimize_permission_tables_update_rls_and_drop_old_tables_v2.sql"
echo ""
echo "步骤 5: 创建初始用户"
echo "----------------------------------------------"
echo "在 SQL Editor 中执行:"
echo ""
echo "-- 创建测试用户"
echo "INSERT INTO users (id, name, phone, role)"
echo "VALUES ("
echo "  gen_random_uuid(),"  
echo "  '管理员',"
echo "  '13800000000',"
echo "  'BOSS'::user_role"
echo ");"
echo ""
echo "-- 在 Authentication -> Users 中创建对应的认证用户"
echo "-- Email: admin@example.com"
echo "-- Password: 设置密码"
echo "-- 复制生成的 User UID，更新上面的 gen_random_uuid() 为实际的 UID"
echo ""
echo "步骤 6: 测试连接"
echo "----------------------------------------------"
echo "运行: npm run dev:h5"
echo "访问: http://localhost:10086"
echo "使用创建的账号登录测试"
echo ""
echo "================================================"
echo "需要帮助？查看文档: docs/DEVELOPER_GUIDE.md"
echo "================================================"
